### PR TITLE
Update overview list

### PR DESCRIPTION
**Pull request by mueller-ma**
* Increase text size
* Increase text padding
* Update unread status
* Add colon between comic number and title

### CODE REVIEW

**Comment by tom-anders** [comment]
Looks cool! But I've noticed a crash when switching from list view to card view, that wasn't there before. Can you have a look at this?

**Comment by mueller-ma** [comment]
Sure. Can you post the stack trace?

**Comment by mueller-ma** [comment]
I cannot reproduce the crash.

**Comment by tom-anders** [comment]
Sorry, didn't have time to test this again yet, will do this week hopefully

**Pull request closed without merging**
