### PR TITLE
Color navigation bar based on day/night theme

### LINKED ISSUE #201: Color navigation bar based on day/night theme
Currently the app has a preference to color the [navigation bar](https://material.io/design/platform-guidance/android-bars.html#android-navigation-bar) based on the primary color. IMO it's better to color the navigation bar unconditionally based on the background: white in the day theme (if the api supports a light nav bar) or dark grey in the night theme.
Google apps also do it this way.

@tom-anders With your ok, I'd start working on this.

### PR DESCRIPTION
**Pull request by mueller-ma**
Closes #201

@tom-anders Can you test this on Android 10, both in day and night theme, and post screenshots? My emulator setup is currently broken...

### CODE REVIEW

**Comment by tom-anders** [comment]
Doesn't seem to work, I always get the light navigation bar, no matter what theme is set

**Comment by tom-anders** [comment]
Also, if the system is in night theme, the whole app should probably use the night theme, right?

**Comment by mueller-ma** [comment]
> Doesn't seem to work, I always get the light navigation bar, no matter what theme is set

Ok, I've to look at it myself then.

> Also, if the system is in night theme, the whole app should probably use the night theme, right?

Yes, the app should, but that's not implemented yet. I want to open a new issue with a few ideas about the theming in the app and how it can be improved, but I didn't had time for it yet.

**Comment by tom-anders** [comment]
> Yes, the app should, but that's not implemented yet. I want to open a new issue with a few ideas about the theming in the app and how it can be improved, but I didn't had time for it yet.
 Yeah I know, that was just a suggestion. Looking forward to your ideas

**Comment by mueller-ma** [comment]
I tested it and it seems to work (Comic cut out to avoid copyright claims):
Screenshot_20200611-094826
Screenshot_20200611-094835

**Comment by tom-anders** [comment]
Ah sorry, it works for me too. I thought it would use the system setting for day/night, but it's actually the app's setting, alright

**Pull request merged**
